AllCops:
  Include:
    - '**/Rakefile'
    - '**/Capfile'
  Exclude:
    - 'db/migrate/**/*'
    - 'vendor/**/*'

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/GuardClause:
  Enabled: false

Style/LineLength:
  Max: 100

Style/NumericLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/SignalException:
  EnforcedStyle: only_raise

Style/ClassLength:
  Enabled: false

Style/MethodLength:
  Enabled: false

Style/FormatString:
  EnforcedStyle: percent

Style/GuardClause:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false
